server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://mydatabase.clwok88809nc.eu-west-1.rds.amazonaws.com:5432/mydatabase
    driver-class-name:  org.postgresql.Driver
    username: postgres
    password: Javacoder

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true